### ISSUE TITLE
filetime 코드 리뷰

### ISSUE THREAD

**Issue by 2016722075ChoiSangUk** [2016722075ChoiSangUk/Project2#14]
void filetime1(){
    time1=localtime(&stat1.st_mtime);
	temp.tm_mon=time1->tm_mon;
	temp.tm_mday=time1->tm_mday;
	temp.tm_hour=time1->tm_hour;
	temp.tm_min=time1->tm_min;
	time1=&temp;
}

void filetime2(){
    time1=localtime(&stat1.st_mtime);
	temp.tm_mon=time2->tm_mon;
	temp.tm_mday=time2->tm_mday;
	temp.tm_hour=time2->tm_hour;
	temp.tm_min=time2->tm_min;
	time2=&temp;
}

**Comment by 2016722075ChoiSangUk** [comment]
해당 코드는 파일의 수정 시간을 localtime 함수를 이용해 구한 뒤, tm_mon, tm_mday, tm_hour, tm_min 필드를 따로 저장하는 함수입니다.

**Comment by LimSH0731** [comment]
코드를 디버깅 해보니 text1의 시간을 받고 text2의 시간을 받으면 시간이 text2의 값으로 덮어쓰기 되는 현상을 발견했습니다.
